version: '3.7'
services:
  licensing-service:
    image: seoleir/licensing-service:0.0.1-SNAPSHOT
    ports:
    - "8080:8080"
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend
    restart: on-failure
  config-server:
    image: seoleir/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    networks:
      - backend
  postgres:
    image: postgres:15.2
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    networks:
      - backend
networks:
  backend:
    name: "licensing-service"
    driver: bridge